index.js

- removed pragma (React changed to advocating using .jsx instead, a while ago)
- dropzone now ignores the hardcoded styling when an explicit classname is passed in
- minor tweak for onDrop, to return an array of files, rather than the incredibly obtuse FileList

Added several improvements

---

index.js

Just used this plugin (which is awesome BTW!) on a project where we wanted drag and drop support but not clicking, and made this change to support that. It means you have to pass in `supportClick={true}` to turn the click support. What do you think? Be happy to change the approach but probably quite useful to be able to customise this stuff?

Turn off onClick support by default

---

index.js

Example: <Dropzone multiple={false} onDrop={this.onDrop} size={150}></Dropzone>
Currently just takes the first file in the dropped array if the user drops multiple files. (I don't think it's good to disallow dropping if the user tries to drop several files on the drop zone.)

Support setting multiple to false to enable single file drop/pick

---

index.js

I figured the user-written onDrop method could use the event. I myself needed it for some jQuery callbacks. This modification doesn't break any existing functionality - `onDrop` methods written with the single `files` parameter will continue to work - just that including an extra event will allow users access to it.

Add optional event parameter to onDrop

---

index.js

Inputs with a type of `file` store the file path in their value and if you select the same file again, you need to clear out the value so that the correct drop events can retrigger. Ran into this issue when a user was adding a file, deleting it via our file manager and then re-adding that file afterwards. This simply clears the input value before attempting to click it.

Clear out file input before click to allow user to select same file again

---

README.md
index.js

I added an explicit `noDefaultStyles` prop to make it clear what's happening when someone doesn't want to use the default `style` object (for example, when using a custom CSS class). 
I found using `style={{}}` cryptic and unclear for anyone else looking at the code, not to mention that it wasn't obvious that I needed to pass in an empty object to get my CSS working properly in the first place (see https://github.com/paramaggarwal/react-dropzone/issues/42).
I also added separate `width` and `height` props for better, basic, control over the size of the Dropzone element (not everyone wants a square). But I left the original `size` prop for backwards compatibility and as an easy alternative if you *do* want a square.
I reformatted the render return value onto multiple lines to make it …

Optionally disable style object in a clearly explicit manner and control size better with `width` and `height` props.

---

index.js

Adding a display name to avoid the component to display as Unknown in React Developer Tools

Adding a display name to avoid the component to display as Unknown

---

index.js

Right now `react-dropzone` adds a class of `active` while dragging a file over the component. The issue is that due to the global nature of css if you have an `.active` style defined in any other stylesheets it's styles will get applied to the `react-dropzone` instance.
Allow passing in the `activeClassName` as a prop this way if you can choose a globally unique classname (by using something like css modules) for the active state.

allow passing in custom activeClassName

---

index.js

If you add an activeClassName it get added to the base className.
It should get added with a space so they stay as separate classes.
This is a bug fix for related to https://github.com/paramaggarwal/react-dropzone/pull/55.

Add a space before active classname

---

index.js

in react 0.14, a warning is thrown when you pass children to a tag that HTML standards say is self closing.

make input a self closing tag and move position of children

---

README.md
index.js
webpack.config.js

This change allows for setting the 'activeStyle' independently of the 'style'. This is for cases where someone might want to use css classes to define the base style and but use inline-styles for the OnDragOver case.
Also included is a webpack config for building out a module that can be included in a <script> tag (instead of using `require`). 
Thanks!

webpack config + allow for using 'activeStyle' independently of 'style'

---

index.js

The component works fine with text children, but when DOM elements or components are added as children the hover-active state is not maintained since the `onDragLeave` event fires when moving over children.
A solution is complicated by the fact that the order in which the `onDragEnter` and `onDragLeave` events fire on the top most element and its children is non-deterministic and depends on the speed with which the mouse moves over the various elements.
However, in the end, once you have left the parent the same number of elements entered must have been left as well, so counting the events on the way in and out turns out to be an effective way to solve the problem.
I'd love to hear your comments.

Maintain drag-active state while hovering child elements.

---

index.js

Hi, it's just a simple patch to make the component work in NWJS environment.
When using jsx transforms and other react magic in an nwjs app, in certain cases global scopes are mixed up, so I made it explicit that that the `URL` object has to be read from `window` variable, not from node's `global`

Make it work in nwjs environment

---

README.md
index.js

I am using this component to hash files in the browser.
Because hashing a file is a streaming process, it doesn't need to read the whole file to process it : thus I can drop bigger files in the drop zone.
Unfortunately right now the preview creation inside the component makes it impossible to handle big files (>100Mo)

Add disablePreview prop to support big files that don't need preview

---

index.js
mocha-environment.js
package.json
test.js

Fixes #108
- Add support for dynamic props on root element
- Add support for dynamic props on input element (via inputProps prop)
- Write basic tests for dynamic props
- Added `react-testutils-additions` as a dev dependency, for $ style find selectors
- Fix babel reference in mocha-environment (could not run tests from a clean install otherwise)
- Fix babel reference in npm build script to use local installed babel

Support additional props on root element and file input

---

README.md

They can be a single MIME type or a comma delimited list. It's not something that I could easily find without some digging, so I thought it would be useful to provide this shortcut info right away.
Closes #141.

Add more MIME type examples

---

.babelrc
.gitignore
mocha-environment.js
package.json
webpack.config.js

Tweaked the build environment:
* Upgraded to babel6.
* Removed the "loose" parameter in babel, since it's not recommended.
Testing shows no  behaviour difference in the resulting code.
* Added a webpack step to generate a ES5 and <script> friendly module
(webpack is also a devDependency now).
* Added a uglifyjs step to minify the bundle (uglifyjs also a
devDependency now)
react-dropzone can now be hosted on a CDN and used directly in a
<script> tag, although the package attr-accept must also be referenced.
Maybe bake it into the code with webpack?

Update build environment (#112)

---

webpack.config.js

fix issue `Cannot find module "React"`
https://travis-ci.org/okonet/react-dropzone/builds/120584465#L205

fix #159 require 'React' instead of 'react'

---

index.html

Add clarity to the manual upload click action completion handler.
Sibling PR to [this](https://github.com/okonet/react-dropzone/pull/163)

Manual upload click handler clarity

---

package.json

closes #165
- tests pass with react v15
- a `react-dropzone` component I have in one of my apps works with react v15

updated react dep to v15

---

README.md

The `onDrop` function is used as the handler for both the `drop` and `click` upload actions. The handler name slightly conflicts across actions, so I wasn't sure if there was an undocumented handler for the manual `open` action. When I looked at the source I could see that `onDrop` was used for both.
As a developer I think I would have found it useful to see that the `onDrop` handler was also the completion handler for the manual open action so I added it to the README.
Thanks for the lib its great! ❤️ ❤️ ❤️

Manual upload handler clarity

---

src/index.js
src/test.js

I had a case where I needed to override the `event.dataTransfer.effectAllowed` on dragStart, so this PR allows us to optionally pass in a function to handle such a thing.
```
onDragStart (e) {
e.dataTransfer.effectAllowed = "move";
},
render () {
return <Dropzone onDragStart={this.onDragStart}></Dropzone>
}
```

Optionally handle onDragStart event

---

src/index.js

A follow-up of: https://github.com/okonet/react-dropzone/pull/194

Remove more custom properties before passing them to wrapper element

---

src/index.js
src/test.js

added maxSize and minSize validation #104

---

package.json
src/test.js

React [issue #7198](https://github.com/facebook/react/issues/7198) was fixed in [React 15.2.1](https://github.com/facebook/react/blob/master/CHANGELOG.md#1521-july-8-2016), so it's safe to run the `.skip`ed test. This will check the React version and run the test if the user is running React 15.2.1 or higher.

Conditionally skip test based on React version

---

src/index.js

This PR removes maxSize and minSize from wrapping `<div>`.
The contribution in #202 missed adding `maxSize` and `minSize` to the [list of `customProps`](https://github.com/okonet/react-dropzone/blob/c6f072a1317474b907f06379606b5ae826b9cac1/src/index.js#L220). Due to that React is throwing a warning:
`Warning: Unknown prop `maxSize` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop`
This PR should fix that.

Unknown prop `maxSize` / `minSize` on <div> tag.

---

README.md
src/index.js
src/test.js

Currently it's not possible to distinguish between accepted and rejected files. The `onDrop` and the `onDropAccepted` functions gets only called with the accepted files. The `onDropRejected` function on the other side gets only called with the rejected files. But sometimes it's useful to react to both states.
This pull request implements the feature in a backward compatible way. The `onDrop` function gets the rejected files passed as second parameter. The `onDropAccepted` and the `onDropRejected` functions behaves the same.

Separate accepted and rejected files

---

src/index.js
src/test.js

You were right with the [bind issue](https://github.com/okonet/react-dropzone/pull/250#discussion_r82737534). I've looked on the wrong code. The `allFilesAccepted` method was not covered by a test. I've added one.

Bind fileAccepted method

---

src/index.js

Dragging an item into the dropzone area causes JS errors in the hover state (though dropping the file works, and the file is successfully uploaded. It may be the case that MS browsers don't really support dropEffect in the way that we'd like it to:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/5184459/
The simplest solution is to remove the "dropEffect" line entirely. A future version might attempt some sort of feature detection before trying to set the dropEffect value.

remove dropEffect, as it causes errors in MS Edge/IE11

---

package.json

Default semantic-release makes bigger releases not possible
since it is always does a release when merged to master.
It also doesn't allow writing custom changelog content for bigger changes.
semantic-release-tamia allows that so trying it out.

Chore: Switch to semantic-release-tamia

---

src/index.js
src/index.spec.js

I went ahead and fixed the spec as requested here: https://github.com/okonet/react-dropzone/pull/322
This allows preview of PDFs and other files (a feature that used to exist, but was removed.)

Remove filetype check for preview (with specs fixed)

---

src/index.js
src/index.spec.js

Scenario that I have is that list items are drop targets but users can also select items in the list by clicking on them. In 3.9.1 click events are not being received by the list items as they are swallowed by the dropzone.
Let me know if you would like anything changed, thanks.

fix(onClick): don't swallow click events when disableClick is true

---

src/index.js
src/index.spec.js

When the child content can vary according to whether the drag is active, such as putting an overlay in front of it or replacing some content, it's possible to get an initial dragEnter event when you drag onto that content, but you'll never get a corresponding dragLeave event, so the enter counter gets thrown off and the dragActive styles never go away.
* Track which elements have been the targets of `dragEnter` events
* On receiving a `dragLeave` event, remove from that list any DOM elements which are no longer part of the current container
* Add test case for this

Fix dragLeave handling when children change (#370)

---

README.md
src/__snapshots__/index.spec.js.snap
src/index.js
src/index.spec.js

* New option `allowGlobalDrops` - if true - will allow dropped items to potentially take over the browser window
* If false, the new default behavior, it will instead install document event handlers to prevent this from happening

Disallow dropping file outside of the Dropzone by default (#87)

---

README.md
src/index.js
src/index.spec.js

**Summary**
Allow use accepted files and rejected files as props in children components.
```js
<Dropzone accept="image/*">
{({ acceptedFiles }) => (acceptedFiles.length && <img src={acceptedFiles[0].preview} />)};
</Dropzone>
```

Feature: Expose acceptedFiles and rejectedFiles to children

---

src/index.js
src/index.spec.js

Since Firefox always returns a type of 'application/x-moz-file', until https://bugzilla.mozilla.org/show_bug.cgi?id=1342057 is implemented correctly on their side, the best we can do is treat that type as always accepted. A false positive is better than a false negative in this case, and brings behavior parity with Safari, which does not support file types at all.
**Summary**
Provide a workaround for https://github.com/okonet/react-dropzone/issues/362 that leads to less user confusion.
No

fix: Don't display bogus Firefox drag types as rejected

---

README.md

Updated readme to also include reject styling options.
The readme only included the active styling options. Now the reject styling options rejectClassName and rejectStyle are also in the readme.
**Summary**
When configuring react-dropzone for my project, i spent 30 minutes searching for rejectClassName. Now i added this to the readme so the next developer doesnt have to search that long.
no
no

Updated readme to also include reject styling options.

---

package.json
src/index.js
src/index.spec.js

Fixes #450
^^ had to fix a few tests to be async with the introduction on a `setTimeout` in the click handler.
**Summary**
Please see the issue, #450 for most of the reasoning.  Executive summary:  
In IE11/Edge the file browser dialogue will block code running.  A timeout is necessary here so that `setState` calls in `onClick` and `onDragRejected` won't conflict when batched together.
No.
There was an unrelated code style fix that sorta just happened -- see the very bottom of this diff.

Adjust timing around onClick/onDrag* events in IE11/Edge

---

src/index.js
src/index.spec.js

Currently isDragActive is true only if all files are going to be accepted. This has several implications:
1. This doesn't work in Safari since DataTransfer is empty until the drop event
1. The active state should be applyed based on user interaction independently from validation
Closes #440
Fixes #461
BREAKING CHANGE: `isDragAccept` acts like `isDragActive` before. `isDragActive` is `true` during the drag.

Fix: Always show an active drag state during the drag

---

src/__snapshots__/index.spec.js.snap
src/index.js

Fixes #475.
Note that because `inputAttributes` is placed after user provided `inputProps` when they are merged, users will not be able to override this setting. Since, I can't imagine why someone would want this behavior, this way makes more sense and keeps the code clean.
**Summary**

Set autocomplete="off" on input attribute

---

package.json
src/index.js
src/index.spec.js

Fix: Dragging multiple files when multiple false doesn't apply rejectStyle

---

package.json

Previous limit would fail the build even for tiniest changes like in https://github.com/react-dropzone/react-dropzone/pull/504. It should not fail such PRs.

test: Increase size-limit threshold to 6KB

---

src/index.js

**Summary**
- Protect calling `this.node.contains` when `this.node` is null
- Fix IE11 bug where `onDocumentDrop` gets called with null `this.node` ref
closes #492

fix: Add null check for node in onDocumentDrop

---

.npmignore

**Summary**
Due to the existence of `yarn.lock` in a package published to NPM register, we have problems with using proper versions of `@types/react` in our apps.
No.

Fix: Add 'yarn.lock' to '.npmignore'

---

README.md
src/index.js

**Summary**
Chrome 63 hangs dragging a file onto the drop zone whilst the file dialog is open. 
https://github.com/react-dropzone/react-dropzone/issues/549

Chrome 63 hangs dragging a file onto the drop zone whilst the file dialog is open.

---

src/index.js
src/index.spec.js

**Summary**
The `isFileDialogActive` wasn't changed after onFileDialogCancel() because it was a local variable
No

fix: restore isFileDialogActive to false after the FileDialog was closed

---

webpack.config.js

**Summary**
This pr solves a problem for the umd build with React loaded from the <script> tag as a global library. When including React from the script tag, it is available to the global namespace as the `window.React` object. However, when specifying the external library in webpack `externals: { "react" : "react" }`, it will return an error `Uncaught Error: Cannot find module "react".` since React is not available as a module but instead as a global object. Using `externals: { "react" : "React" }` instead will actually make Webpack fail to build, since the `import React from "react";` statement will not match any module.
It appears a solution, based …

umd build fix

---

src/index.js
src/utils/index.js
src/utils/index.spec.js

- bugfix
- Yes, my code is well tested
- Not relevant
**Summary**
The file chooser does not open on Samsung mobile browser.  Tested on Galaxy S8/S8+/S7 on browser stack.  Wrapping the call to `this.open` in a `setTimeout` is causing the issue.  According to the comments the `setTimeout` was added for [IE/Edge](https://github.com/react-dropzone/react-dropzone/issues/450), so this PR will only wrap `this.open` for IE/Edge.
No
Related to https://github.com/react-dropzone/react-dropzone/issues/450

Wrap open in setTimeout only for IE/Edge.

---

src/index.js

**Summary**
The `accept` prop is handled by `okonet/attr-accept` which can handle an array of strings. This was not accounted for in the prop types leading to an incorrect warning being displayed.
No.

fix: update 'accept' proptype definition

---

README.md
examples/Accept/Readme.md
examples/Basic/Readme.md
examples/File Dialog/Readme.md
examples/Fullscreen/Readme.md
examples/Styling/Readme.md
src/__snapshots__/index.spec.js.snap
src/index.js
src/index.spec.js
src/utils.js

**Summary**
Picking up removal of style management done by @okonet's. Refactored Dropzone to use render props, giving flexibility to users to implement their own styles in userland.
Yes it does. It changes the render signature of Dropzone.
Merging this to https://github.com/react-dropzone/react-dropzone/pull/468 for further review.

Primitive Dropzone with render props

---

package.json
src/index.spec.js
yarn.lock

**Summary**
This PR will clean up some potentially leaky spies by using jests built in mock functions, which can be reset in between tests automatically. It will also remove sinon as a dependency. 
No
see https://github.com/react-dropzone/react-dropzone/pull/645#issuecomment-415094186

Refactor: Replace sinon with jest mock functions

---

src/index.js

**Summary**
Since v4.3 the event passed to the handler is not reusable anymore, because some work is done with it before. To prevent this `evt.persist()` is called.
Fixes #646 
no
I don't really know how to test this.

fix: persist synthetic event

---

examples/Styling/Readme.md
src/index.js
src/index.spec.js

**Summary**
Fixes https://github.com/react-dropzone/react-dropzone/issues/647.
If using a render function as a child of `Dropzone`, the `acceptedFiles`/`rejectedFiles` properties were always passed as `[]` and were never updated. The reason for the bug is explained [in the issue above](https://github.com/react-dropzone/react-dropzone/issues/647#issuecomment-423863500) and reproduced here:
> `renderChildren` is [calling the render function passing in a shallow copy of its inner `this.state`](https://github.com/react-dropzone/react-dropzone/blob/master/src/index.js#L296); however, while [initialized as empty …

fix: set accepted/rejected files state on drop

---

src/index.js
src/index.spec.js
src/utils/index.js
src/utils/index.spec.js

**Summary**
As this library only covers drag 'n drop of files, accidentally dragging text or html elements should not trigger any of the handlers attached to the dropzone (e.g. `onDragEnter`, `onDrop`, etc.).
A similar issue is also reported in https://github.com/react-dropzone/react-dropzone/issues/599.
Yes

Do not call any of the onDrag*/onDrop handlers if the user is not dragging files

---

typings/react-dropzone.d.ts
typings/tests/basic.tsx

They're marked as required, but the `propTypes` only mark it as optional. One of them is wrong :)
**Summary**
When used with TypeScript it's currently required for `DropZone` to have a child, even if that child is just `{undefined}`.
No

Mark children as optional in the typings

---

examples/Basic/Readme.md
examples/Fullscreen/Readme.md

**Summary**
When attaching files to the Fullscreen example, you would get console warnings due to missing `key` props on the dropped files list items.
No
None

docs: add missing key to fullscreen example

---

examples/FileDialog/Readme.md
src/index.js
src/index.spec.js
typings/react-dropzone.d.ts

**Summary**
If you are rendering a Dropzone using a child function, you can open the file dialog programmatically without having to also add a ref.
https://github.com/react-dropzone/react-dropzone/issues/691
No
I updated the TypeScript definition, though I've never used TypeScript before so I just guessed on the syntax. Hopefully someone with more experience can take a look at it and see if that is correct?

feat: add open() to child func props (#691)

---

src/index.js
src/index.spec.js

**Summary**
A potential fix for: https://github.com/react-dropzone/react-dropzone/issues/689
Nope

fix: call setState before callbacks

---

src/index.js
src/index.spec.js

**Summary**
We encountered an issue that was described here, #40, that describes attempting to load the same file twice (the data has changed). The use-case where we encountered this was a user uploaded a file, but the rejected it due to formatting issues. The file input doesn't discard the target state so uploaded the correct file moments later does not trigger any handles such as `onDrop`, etc....
Summary of changes:
1. Update that event is passed to `onClick` prop handler inside of
`onInputElementClick`
2. Update `'should invoke inputProps onClick if provided'` testcase to
verify that function is now called with a MouseEvent object
**Does this PR …

fix: pass event to user-supplied inputProps {onClick}

---

src/index.js
src/index.spec.js
src/utils/index.js
src/utils/index.spec.js
src/utils/styles.js

**Summary**
We currently rely on getting the data transfer data to detect what kind of data is being dragged. While that works in Chrome, Firefox and Edge, it does not work in Safari.
Hence this PR which uses [{types}](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/types) to do the data type detection.
And a few other things:
- apply different active styling when file type cannot be inferred (to avoid confusion, reported in https://github.com/react-dropzone/react-dropzone/issues/668)
- cleanup some of the tests
No.

fix: improve drag type detection and fix styling in Safari

---

typings/react-dropzone.d.ts
typings/tests/plugin.tsx

**Summary**
`getDataTransferItems()` can also be called with a change event that originated from an `<input>`, this PR adds the proper types to reflect that.
No.

fix: fix types for getDataTransferItems()

---

examples/Nesting/Readme.md
src/index.js
src/index.spec.js
styleguide.config.js

**Summary**
This addresses the issue explained in https://github.com/react-dropzone/react-dropzone/issues/686 and also:
- persist event in callbacks where the event is passed down the custom callbacks
No.

fix: fix event propagation and close #686

---

README.md
examples/Previews/Readme.md
package.json
src/index.js
src/index.spec.js
styleguide.config.js
testSetup.js
typings/react-dropzone.d.ts
typings/tests/all.tsx

**Summary**
Remove the preview generation for files.
The dropzone should not be responsible for enhancing the File object with whatever the user needs. The user is free to manipulate the File objects as they wish after the `onDrop()` callback emits them.
Yes. The `{preview}` property on the File object will no longer be generated. And the `{disablePreview}` property on the Dropzone is also removed.
Creating previews can easily be achieved in the `onDrop()` callback:
```js
class MyZone extends React.Component {
onDrop = files => {
this.setState({
files: files.map(file => ({
...file,
preview: …
```

refactor: remove file preview and close #705

---

examples/Basic/Readme.md
src/index.js
src/index.spec.js

**Summary**
Do not invoke `{onFileDialogCancel}` cb if no files were selected when the file selection dialog is closed (fix for #652).
No.

fix: fix on file select dialog close behaviour

---

src/index.js
src/index.spec.js

**Summary**
It seems that drag and drop while the file select dialog is opened does not crash in Chrome anymore. So I reverted the current fix as it seems to confuse some users (see https://github.com/react-dropzone/react-dropzone/issues/723).
No.

fix: allow drag drop while file select dialog is opened

---

examples/Events/README.md
examples/FileDialog/Readme.md
examples/Fullscreen/Readme.md
src/index.js
src/index.spec.js
typings/react-dropzone.d.ts
typings/tests/all.tsx

**Summary**
Removed [prop-types-extra](https://github.com/react-bootstrap/prop-types-extra) as the lib bundle contained a node specific var (`process`) and broke some apps that used this lib with a `<script>` tag.
Remove deprecated prop {disableClick}. To prevent the default behavior of click just use idiomatic js:
```js
<Dropzone>
{({getRootProps}) => (
<div {...getRootProps({onClick: evt => evt.preventDefault()})}>
Drop some files here
</div>
)}
</Dropzone>
```

fix: remove deprecated() lib and close #764

---

typings/react-dropzone.d.ts
typings/tests/refs.tsx

**Summary**
I missed adding typings for `{ref}` on the `<Dropzone>` component in one of the previous PRs. This PR fixes that.
No.

fix: fix typings for {ref} and close #798

---

examples/events/README.md
examples/file-dialog/README.md
src/index.js
src/index.spec.js
typings/react-dropzone.d.ts
typings/tests/all.tsx

**Summary**
Bring back the `{disableClick}` prop (with a different name) as using idiomatic js causes some other issues in the user land (e.g. `event.stopPropagation()` will stop events from being propagated to children, see #783).
Alongside that, also introduce:
- `{noKeyboard}` to disable keyboard events (SPACE/ENTER to open file dialog, focus/blur state)
- `{noDrag}` to disable drag events
- `{noDragEventsBubbling}` to stop drag events propagation to parents
No.

feat: add {noClick}, {noKeyboard}, {noDrag} and {noDragEventsBubbling}

---

src/index.js
src/index.spec.js

**Summary**
We use an effect to set the dropzone ref when using the `<Dropzone>` component, but we did not cache, so if a cb function was provided, it would be called whenever react ran through all effects. This PR addresses that issue.
No.

fix: cache effect for setting the ref and close #806

---

src/index.js
src/index.spec.js

**Summary**
Address https://github.com/react-dropzone/react-dropzone/issues/182, which prevents click events from being triggered when the dropzone is wrapped in a `<label>` without the `for` attribute.
No.

fix: prevent click on input when propagated form a <label>, close #182

---

typings/react-dropzone.d.ts
typings/tests/basic.tsx

**Summary**
Small change to type definitions of `files` from `File` to `FileWithPath`.
Motivation is that I receive type errors when trying to access the `path` property in the `acceptedFiles` array returned from `onDrop` as they are incorrectly typed as `File`.
**Does this PR introduce a breaking change?** 
No, as `FileWithType` extends `File` (only difference is optional `path` property)

fix: change typescript types to FileWithPath instead of File

---

src/index.js

**Summary**
If someone sets `disabled: false`, they want the input to be _not disabled_. That is, they want it to be enabled.
But `false || noClick` always returns `noClick`, so the `noClick` setting wins.
Without this change, there's a bug:
* set `noClick: true`
* set `onClick={open}` on a button somewhere
* since the input is disabled, clicking it does nothing, and the file picker cannot be opened
Code to create this situation:
```js
const { getRootProps, getInputProps, open } = useDropzone({ noClick: true })
return (
<div {...getRootProps()}>
<Button onClick={open}>Upload</Button>
<input {...getInputProps({ disabled: false })} />
</div>
)
```
This …

Enable disabling disabled

---

src/index.js

Potential fix for issue #853 - *programmatic open not working in the demo site*
- [+] bugfix
- [+] Not relevant
That is just an example of a potential fix...
*NOTE:* We are still using `noClick` prop in the documentation for [Opening File Dialog Programmatically](https://react-dropzone.js.org/#opening-file-dialog-programmatically) example

fix(issue 853): opening file dialog programmatically

---

src/index.js

**Summary**
This is a potential fix for #876. Ideally, the dragged files stored in the component state would be replaced by a data structure that the browser isn't going to modify, but this would be a breaking change since `draggedFiles` gets returned by the `useDropzone` hook and thus can be used directly by consumers of this library. Instead, we can work around the problem by changing `dragTargets` to be stored in a ref rather than the state, which eliminates the re-render that occurs after `draggedFiles` has been cleared out by the browser and before a new `draggedFiles` gets returned. It's not a perfect solution, since the problem could still occur …

Fix for #876: Dropping file into child element of drop zone opens it

---

README.md

**Summary**
Replaces reference to _readAsBinaryString_ method, which is deprecated,  with readAsArrayBuffer is the current recommended API.
Fixes https://github.com/react-dropzone/react-dropzone/issues/871

README: readAsBinaryString (deprecated) --> readAsArrayBuffer (Fixes issue #871)

---

src/index.js
src/index.spec.js
src/utils/index.js

**Summary**
[ISSUE](https://github.com/react-dropzone/react-dropzone/issues/921)
Fixed issue with `isDragReject` and `isDragAccept` when `multiple` is false and `acceptedFiles` are empty. Updated resolution of those two properties which are inlined with `acceptedFiles`.
No.
I have updated the tests for these changes.

fix: isDragReject consistent with onDrop, close #921

---

src/index.js
src/index.spec.js
src/utils/index.js
src/utils/index.spec.js
typings/react-dropzone.d.ts

- [X ] feature
- [X ] Yes, my code is well tested
- I will update the documentation in a separate PR once this PR is merged. *Question for maintainers:* That PR should go to the `gh-pages` branch, correct?
**Summary**
See conversation in #752 
Yes. The method signatures of `onDrop` and `onDropRejected` as well as the return value of `useDropzone` were changed in order to add the reasons why rejected files were rejected.
`onDrop` BEFORE this change:
```
onDrop?<T extends File>(acceptedFiles: T[], rejectedFiles: T[], event: DropEvent): void;
```
`onDrop` AFTER this change:
```
onDrop?<T extends …
```

feat: add reject reasons to onDrop, onDropRejected callbacks

---

examples/styling/README.md

**Summary**
Just noticed a small mistake in the styling example. The `isDragAccept` prop was missing in the memo hook.

Missing "isDragAccept" in styling example memo hook

---

src/index.js
src/index.spec.js

**Summary**
This PR fixes issues #911 and #526 
The issue is that when dragging over an element containing a text node, Firefox fires an event when entering the element and then another one when entering the text node.
This can be seen with this fiddle: https://jsfiddle.net/493wmzvL/2/
With React the behavior is similar however both the text node and its container fire an event with the same contents in `event.target`. This can be seen in this fiddle: https://jsfiddle.net/wqcsg2un/2/
I don't know if it is expected behavior from React or not, I will ask over there.
My suggested fix is to always add elements when `dragEnter` is fired and remove elements …

fix: #911 isDragActive value when dragging over text on Firefox

---

typings/react-dropzone.d.ts

**Summary**
This is more correct for TS strict mode.
See info in [@typescript-eslint/method-signature-style](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/method-signature-style.md)
It also is compatible with the [@typescript-eslint/unbound-method](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/unbound-method.md) rule.
Currently this
```tsx
const { getRootProps } = useDropzone();
```
is viewed as a method that's been pulled out of a "class" that potentially uses `this`. Calling it directly like this would change the scope and break it. We know …

[types] Define functions as properties

---

examples/maxFiles/README.md
examples/number-of-accepted-files/README.md
src/index.js
src/index.spec.js
styleguide.config.js
typings/react-dropzone.d.ts

**Summary**
This PR is created base on a user [suggestion  ](https://github.com/react-dropzone/react-dropzone/issues/999)that too many files cause freezing or even crash the browser.
one solution would be a limited number of files.
So I added `maxNumber` prop.
_How is it works?_
When `multiple` prop is true we can pass `maxNumber` witch limit the number of files that DropZone accepts.
The minimum accepted value is `2`.
I doubt naming to choose `maxFiles` or `maxNumber`, please tell me if `maxFiles` is a better choice.   
This is the main part of this PR:
```javascript
if (multiple && maxNumber>1 &&  acceptedFiles.length > maxNumber) {  
// Reject …
```

feat: add maximum number of accepted files

---

src/index.js

**Summary**
Hello! This PR simply moves the default props from the hook to the defaultProps property on the Dropzone component, so that the defaults can be documented on the documentation site.
No!

docs: move default props to Dropzone component for react-docgen

---

.gitpod.yml
README.md
styleguide.config.js

Hi.
I work for Gitpod. This PR adds gitpod config to the repo to make contributions easier for newcomers i.e with a single click it will launch a workspace and automatically:
- clone the `react-dropzone` repo.
- install the dependencies.
- run `yarn build` and `yarn start`.
This can be helpful for beginners i.e they can start coding instantly without setting anything up.
You can give it a try on my fork of the repo via the following link:
https://gitpod.io/#https://github.com/nisarhassan12/react-dropzone
This is how it looks:
**Summary**

make contributions easier with the online automated dev setup

---

src/index.js
src/index.spec.js
src/utils/index.js
src/utils/index.spec.js

**Summary**
There is a bug in maxFiles feature that `isDragReject` doesn't change when DragEvent contains more than the max number of files
This bug reported #1017 
shouldn't

bug:change isDragReject true when maxFiles rejectDrag

---

src/index.js
src/index.spec.js

**Summary**
Fix for https://github.com/react-dropzone/react-dropzone/issues/1025 
Adds `maxFiles` as a dependency to `onDropCb` callback, so that changes to `maxFiles` parameter are reflected in the behaviour of that function.
No

Fix: make sure changes to maxFiles prop are reflected in behaviour

---

typings/react-dropzone.d.ts

**Summary**
In the Validator readme.md, it says:
>The value must be a function that accepts File object and returns null if file should be accepted or error object/array of error objects if file should me rejected.
The issue is, with the current TypeScript bindings, returning `null` isn't a valid return type. 
This PR fixes this.

Fix Validator Type

---

src/index.js

**Summary**
A green "plus" symbol shows when dragging links and other non-file items across a dropzone. This is particularly noticable if you combine `react-dropzone` with a draggable library like `react-dnd`, but it's also noticeable in the examples even in the docs.
closes #1042

fix: Check drag event contains files before showing "copy" cursor

---

typings/react-dropzone.d.ts

Modified type definitions for getRootProps and getInputProps to:
- accept a parameterized type that extends DropzoneRootProps and DropzoneInputProps respectively
- which allows for more meaningful type information to be passed from getRootProps and getInputProps to their respective components
Example:
```ts
interface IStyledProps {
isDragActive: boolean;
isDragAccept: boolean;
isDragReject: boolean;
}
const getColor = (props: IStyledProps) => {
if (props.isDragAccept) {
return "#00e676";
}
if (props.isDragReject) {
return "#ff1744";
}
if (props.isDragActive) {
return "#2196f3";
}
return "#eeeeee";
};
const Container = styled.div<IStyledProps>`
...
border-color: ${(props) => getColor(props)};
...
`;
const DropzoneUploader: FunctionComponent = () => {
const {
getRootProps,
getInputProps, …
```

fix: Modified type definitions for getRootProps and getInputProps

---

src/index.js

**Summary**
We can just use initial state state instead of copy so many state into the reset code block.

fix: use initial state when reset state

---

.npmignore

**Summary**
This fixes #1076. This PR is presented as an alternative to #1083.
`react-dropzone` is apparently intended to be compatible with the Doka image editor ([now called "Pintura" apparently](https://pqina.nl/pintura/)), which explains why it's potentially desirable to have `doka` code in the repository for the purposes of evaluating this compatibility. However, `react-dropzone` should not be redistributing `doka`'s own code, which is released under [this specialist licence](https://pqina.nl/pintura/license/), as `react-dropzone` itself is [released under the MIT licence](https://github.com/react-dropzone/react-dropzone/blob/master/LICENSE), and …

Stop shipping the vendor directory

---

src/utils/index.js
src/utils/index.spec.js

**Summary**
In https://github.com/react-dropzone/react-dropzone/pull/1061, the `ErrorCode` enum was introduced to the Typescript definitions, but it was never added to the runtime script. This adds it to the `utils.js` file so it can be accessed without throwing an import error.
Fixes https://github.com/react-dropzone/react-dropzone/issues/1091
No

Add ErrorCode object to runtime

---

src/index.js

**Summary**
Fixes https://github.com/react-dropzone/react-dropzone/issues/1094 - needs to re-export the `ErrorCode` from `utils` to make it available and match the Typescript definitions.
No.

Re-export ErrorCode from './utils'

---

README.md

**Summary**
In reference to [this issue](https://github.com/react-dropzone/react-dropzone/issues/1085), I thought it'd good if we have a line in the documentation to _remind_ users that they need to take care of making the dropzone accessible.

docs: add a line to inform users where to pass accesibility props

---

src/index.js
src/index.spec.js
typings/react-dropzone.d.ts
typings/tests/all.tsx
typings/tests/file-dialog.tsx

**Summary**
I needed to push monitor events when the file chooser showing up. We did have onDragEnter/Leave to understand users can drag files instead of using the file chooser to select files. It would be beneficial to have this callback for the situation.
No. 

added onFileDialogOpen callback

---

examples/styling/README.md

**Summary**
In the Styling example, the active drag style is always overridden by either the drag accept or reject style when a file is dragged over the component. This change updates the active drag style to instead be used when the component is focused, to match the Basic example. When the components are clicked/focused, their border colors will be blue.
No.

[Documentation] Move unused active drag style to be used on focus instead

---

package.json

Declare module as side effect free to assist webpack tree shaking.
**Summary**
We're using react-dropzone in our UI library that is used across various microfrontend modules. Unfortunately react-dropzone doesn't tree-shake away when a module is not using the dropzone part of our UI library.
No

Declare module as side effect free

---

README.md
examples/events/README.md
package.json
src/index.js
src/index.spec.js
src/utils/index.js
src/utils/index.spec.js
yarn.lock

**Summary**
Improve `onFileDialogCancel` behaviour by using the [File System Access API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API) when supported.
No.

feat: use FileSystemAccess API to select files and close #1031 and #1079

---

src/__snapshots__/index.spec.js.snap
src/index.js
src/index.spec.js

**Summary**
Set the `role` attribute to `button` by default on the dropzone.
No.
Gotta merge https://github.com/react-dropzone/react-dropzone/pull/1123 first.

feat: set role attr to button by default on the root and close #1110

---

src/index.js
src/index.spec.js

**Summary**
As discussed in https://github.com/react-dropzone/react-dropzone/discussions/1130, using FS access API introduces a breaking change in how the `accept` attribute works.
This change just adds a new option `useFsAccessApi` (false by default) which can be used to disable using the FS access API.
No.

fix: disable file system access API usage by default and close #1131

---

src/index.js
src/index.spec.js

**Summary**
Enable the [File System Access API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API) by default.
As of this change, the `accept` attribute does not work with file extensions anymore (at least not when picking files using the file dialog). Check https://developer.mozilla.org/en-US/docs/Web/API/window/showOpenFilePicker#parameters for more information.

feat: enable file system access API by default

---

src/index.js
src/index.spec.js

**Summary**
`KeyboardEvent.keyCode` is [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) and should not be used anymore.  
Browsers could drop support anytime and it's not recommended to use it.
I don't think so.

Use "KeyboardEvent.key" instead of "Keyboard.keyCode"

---

src/__snapshots__/index.spec.js.snap
src/index.js

**Summary**
Explain the **motivation** for making this change. What existing problem does the pull request solve?
Try to link to an open issue for more information.
Our project is committed to using Web Content Accessibility Guidelines (WCAG) 2.1 Level AA. In particular, correct semantic elements of the HTML Living Standard should be used.
According to https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete `autocomplete` attribute is available on <input> elements that take a text or numeric value as input. 
Thus using `autocomplete` attribute for `file` input type courses errors while validating for the correct semantic elements of …

[fix] - remove autocomplete for file input type

---

README.md
examples/accept/README.md
examples/pintura/README.md
examples/previews/README.md
examples/styling/README.md
src/index.js
src/index.spec.js
src/utils/index.js
src/utils/index.spec.js
typings/react-dropzone.d.ts
typings/tests/accept.tsx
typings/tests/all.tsx

**Summary**
Allow users to pass the file extensions along the MIME type when the FS access API is supported.
Yes. The `{accept}` prop will now require an object instead of a string or array of strings.
Before:
```js
useDropzone({
accept: ".jpeg,.png"
// accept: [".jpeg", ".png"]
})
```
After:
```js
useDropzone({
accept: {
"image/*": [".jpeg", ".png"]
}
})
```

feat: allow passing file ext. to the file picker options and close #1141

---

src/__snapshots__/index.spec.js.snap
src/index.js
src/index.spec.js

**Summary**
Using aria role `button` seems to be causing more issues than not having it set at all (as it was before we introduced the change). So this PR just switches the value to [presentation](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/presentation_role).
Not for devs. But it does change how end users that use aids perceive it (easily fixed by overriding it).

fix: use aria role `presentation` by default and close #1152

---

src/index.js
src/index.spec.js

**Summary**
If the FS access API is supported, but the app is not running in a secure ctx, we'll try to use the input as fallback. But if this is missing, nothing will happen and the user will be confused. This PR just makes sure to call the `onError` cb if that case occurs.
No.

fix: call onError if FS access API fails in secure ctx

---

src/utils/index.js
src/utils/index.spec.js

**Summary**
Can't accept more than one file type, tried to accept both images and videos and ran into a problem.
**Reproduce**
[Demo on website](https://react-dropzone.js.org/#section-accepting-specific-file-types) - Can't pick png, only first option is available to pick.
No

Fix not able to accept multiple files types

---

src/index.spec.js
src/utils/index.js
src/utils/index.spec.js

**Summary**
This works around https://crbug.com/1264708 by always including a description in the FilePickerAcceptType passed to the options of window.showOpenFilePicker().
Fixes #1127.
Fixes #1222.
Fixes #1190.
no

fix: work around Chromium File System Access API bug

---

examples/forms/README.md
styleguide.config.js

**Summary**
This issue https://github.com/react-dropzone/react-dropzone/issues/880 asks reports the files are submitted in form submissions. The answer given is that React-dropzone can't do that. 
This PR adds docs to how you can send the files with form submission events. 
No.

docs: add forms example

---

typings/react-dropzone.d.ts

fix: add path type in acceptedFiles

---

examples/previews/README.md

Fixes linting error: 
> React Hook useEffect has a missing dependency: 'files'. Either include it or remove the dependency array. eslint (react-hooks/exhaustive-deps)
**Summary**
Explain the **motivation** for making this change. What existing problem does the pull request solve?
Try to link to an open issue for more information.
If this PR introduces a breaking change, please describe the impact and a migration path for existing applications.

Add missing dependency

---

typings/react-dropzone.d.ts

Related to https://github.com/react-dropzone/react-dropzone/issues/1400
**Summary**
To be compatible with React 19 typings, where global JSX was removed: https://react.dev/blog/2024/04/25/react-19-upgrade-guide#the-jsx-namespace-in-typescript
Assumed to be unaffected due to type conversion only
ReactElement is more reliable than React.JSX.Element, which “may” be backported in some versions.
See also: similar fixes merged in another library (react-datepicker)
https://github.com/Hacker0x01/react-datepicker/pull/5296

Fix for compatible with React 19

---

package.json
src/index.js

- Add extensions to relative import/export.
- Add `{"type": "module"}` to the ESM build directory.
**Summary**
Explain the **motivation** for making this change. What existing problem does the pull request solve?
Try to link to an open issue for more information.
Allows to `import` the library from Node.js, for example with ESM-native SSR tools like Vite.
If this PR introduces a breaking change, please describe the impact and a migration path for existing applications.
It should not be breaking.
Fixes: https://github.com/react-dropzone/react-dropzone/issues/1259

fix: make ESM build compatible with native Node.js

---

src/index.js
typings/react-dropzone.d.ts

since useFsAccessApi is true by default the types dont caterr for FileSystemFilehandle can also be retuirned
**Summary**
since useFsAccessApi is true by default ,
or in newer versions
the types dont handle the type  FileSystemFilehandle which can also be returned
if user selects useFsAccessApi

fix(event_type): :art: update drop event type to filesystemfile handle
