react-dropzone/react-dropzone

- index.js
Hi, I'm toshipon :smiley: 
Thank you for your good component for dropzone.
I'm using this & implement to be able to click & choose function for that.
I don't know that my change is good for you. 
if you don't feel good for this change, please close this Pull Request. 
I just wanna notice you that I appreciate your great work. 
thank you
> Support click & choose file

- index.jsx
- package.json
Hi to use your great work we need to rename the file otherwise our loader is complaining. Could you please apply my pull request, TIA
> Renaming file to react naming conventions

- index.js
Switched out the JSX for javascript.
See this issue: https://github.com/paramaggarwal/react-dropzone/issues/14
> Switch JSX to Javascript

- index.js
Add the preview property to file object which contains the client-side preview of the just uploaded file. This can come in handy to show thumbnails of just uploaded files.
> Add previews to file objects

- index.js
allow accept attribute for input to be able to specify which MIME-types and/or file extensions are allowed.
References #20.
> allow accept attribute for dropped files

- demo/README.md
- demo/browser.js
- demo/package.json
- demo/script.js
- index.js
- package.json
Fixes the bug encountered in #38, while also making it easier (and more clear how) to build the demo. 
Also updates the way to get a DOM node in React ([component.getDOMNode() is deprecated; React.findDOMNode() should be used instead](https://facebook.github.io/react/blog/2015/03/10/react-v0.13.html#new-features)).
> Improve build

- index.js
Sometimes you need to handle this events on the above level.
> Adding support for DragOver & DragLeave custom callbacks

- index.js
I used the e.stopPropagation() rather than returning false as React gives a warning with the latter.
> onDragOver fix for issue #37

- README.md
> update README to explain accept, multiple, supportClick

- index.js
- package.json
Introduced 2 new callbacks (`onDropAccepted` and `onDropRejected`).
Added `rejectClassName` prop to allow custom styling when drop will be rejected.
Closes #57
> Implemented accept attribute support for dropzone.

- index.js
> Use Chrome's ability to see dragged files without breaking other browsers

- .babelrc
- .gitignore
- package.json
This adds missing React dependency (as peer dependency to prevent double React conflicts) and babel config. It should be tested with React 0.14 though. Probably a major release for 0.14 will be required.
> Add missing React dependency + babel config

- index.js
- package.json
This PR addresses the points raised in #77
> Upgrade package for react-0.14.0, use findDOMNode

- index.js
- package.json
- on older iphones, multiple attribute was causing a lot of issues.
- additionally - rewrote some stuff for better ES2015 compat and amended the npm build script to use `--out-dir` as `-o dir/index.js` was causing ENOENT when `lib` did not exist.
- made events callbacks pass the instance as context for consistency/API.
> Optional multiple support

- index.js
> Decouple reject and active classnames from className

- index.js
Fix to allow server side rendering, document var should always be checked for undefined
> server side rendering fix

- index.js
- mocha-environment.js
- package.json
- test.js
I've added a small fix and created a test environment, using [deep breath] babel, mocha, chai, sinon, jsdom and react-addons-test-utils. Use ```npm test``` to run them, feel free to adapt them to your tastes. Thanks for this project.
ref #102
> fix for disablePreview property not being obeyed

- README.md
Add documentation and a short example for accept option in README to solve #99
> Add accept documentation in README

- src/index.js
> Fix of #74

- src/index.js
> Support one or more children.

- src/index.js
- src/test.js
> Fix off-by-one in droppedFiles length

- package.json
- src/index.js
- src/test.js
> If accept prop is specified, enforce it on drop

- mocha-environment.js
- src/index.js
- src/test.js
Relevant issue: https://github.com/okonet/react-dropzone/issues/193
Not sure if that's the _traditional_ way to go. 
I also fixed a couple additional eslint warnings in the meantime.
Feedback is welcome :)
> Fix unknown props warning in React v15.2

- README.md
Updated readme to include minSize and maxSize #202
> updated readme to include minSize and maxSize features

- src/index.js
> OSX drag issues. Fixes #74, #195, #191

- README.md
Refer to: https://github.com/okonet/react-dropzone/issues/246
> Update README examples to use ref callbacks

- src/index.js
> add acceptedFiles support

- .codeclimate.yml
This PRs adds a config that should work with the current version.
> Integrate with CodeClimate

- src/index.js
- src/index.spec.js
This PR adds `onClick` callback support and fixes #273
> Feat: Add onClick callback

- src/index.js
- src/index.spec.js
> Propagate onDragOver event

- src/index.js
See: https://github.com/okonet/react-dropzone/issues/276
> Add note about mime types

- package.json
- src/index.js
In the next major release, some props will be deprecated. In order to smoothen the migration process deprecation warnings were added.
> Feat: Add deprecation warnings for some props

- package.json
> package.json: Add myself as a contributor

- src/index.js
**Summary**
Add a comment to explain why we are checking for a specific MIME type for Firefox.
No
> fix: Add comment to explain firefox dragover accepted workaround

- README.md
fixes https://github.com/okonet/react-dropzone/issues/398
**Summary**
> call window.URL.revokeObjectURL(file.preview) to avoid memory leak

- package.json
- src/index.js
- webpack.config.js
`React.PropTypes` is deprecated as of React 15.5.
> Use `prop-types` instead of `React.PropTypes`

- README.md
**Summary**
I have need to pass properties to input and see nothing relevant in documentation. So that I have investigated issues and came up with #274 . I decided to update README as mentioned in issue.
No
> Updated README.md according to input attributes

- examples/Accept/Readme.md
documentation
Not relevant
Yes, I've updated the documentation
**Summary**
Better explanation of https://github.com/okonet/react-dropzone/issues/330
No
> docs: Explain vendor differences on how accept work

- examples/Accept/Readme.md
**Summary**
Fixes typo in docs
No
> Fix typo in /examples README

- package.json
- src/__snapshots__/index.spec.js.snap
- yarn.lock
> chore(package): update jest to version 20.0.1

- .eslintrc
- package.json
- src/getDataTransferItems.js
- src/getDataTransferItems.spec.js
- src/index.js
- src/index.spec.js
- styleguide.config.js
- testSetup.js
- wallaby.config.js
- webpack.config.js
- yarn.lock
**Summary**
Use prettier in a pre-commit hook with lint-staged
No
> Use eslint-config-okonet and prettier

- package.json
> chore(package): update react-styleguidist to version 5.4.0

- package.json
> chore(package): update react-styleguidist to version 5.4.1

- package.json
> chore(package): update react-styleguidist to version 5.4.2

- .vscode/settings.json
- src/index.js
- src/index.spec.js
**Summary**
This fixes https://github.com/okonet/react-dropzone/issues/252
Nope no breaking change unless someone took advantage of it being called twice.
> Bugfix for issue #252, onClick event being called in input twice. 

- package.json
**Summary**
React 16 beta is out now and the peer dependencies for this package don't allow it to be used. I've changed it now so that React 16 is supported.
No breaking changes.
> React 16 support

- examples/File Dialog/Readme.md
> Fix the spelling mistakes.

- README.md
Add a warning to the readme that shows how to read file content on recent browsers.
**Summary**
> Update README.md - FileReader API

- .github/stale.yml
> chore(stale): Add pinned to excluded label

- package.json
- yarn.lock
closes #495
**Summary**
Add Size limit to local and ci builds to ensure we don't surpass the limit of the library
> chore(size-limit): Add size-limit

- examples/Fullscreen/Readme.md
**Summary**
Without the `position: "relative"` style on Dropzone component, the overlay comes at the top of the page, which might be confusing for people trying to drag and drop to play, and not being able to see the overlay.
No
> Fixes the overlay

- src/index.js
- src/index.spec.js
**Summary**
Better coverage I think
No
> test: Add more tests

- src/index.js
**Summary**
Similar to https://github.com/google/google-api-nodejs-client/issues/375, this PR removes the `delete` operator in favor of object destructuring for better perf.
No
> style: Avoid delete operator

- README.md
**Summary**
Fix indentation on readme file
No
> Fix readme example indentation

- .github/stale.yml
- package.json
- src/index.spec.js
- src/utils/index.js
- webpack.config.js
updated webpack config and build on umd for production. also converted utils to es6 arrow functions
- [x ] build / chore
- [x ] Yes, my code is well tested
- [x ] Not relevant
**Summary**
This solve is to implement a production ready component for end users. It also lowers the size of the component for consumption. 
#531 
Also to be more ES6 complicit I updated the utils to arrow functions.
> build: Webpack production changes

- src/index.js
**Summary**
Per [#560] a TypeError is thrown because `this.fileInputEl.files` is referenced in cases where `this.fileInputEl` is null.
I also fixed 3 eslint errors that address comment indenting/whitespace.
no
>  fix: check for null [#560] && fix lint errors

- src/index.js
- [+] documentation
- [+] Not relevant
- [+] Yes, I've updated the documentation
**Summary**
Wasted some time for test, in what exactly is minSize and maxSize calculated.
W/O issue.
No braking changes.
> clarified the documentation

- src/index.js
> minor changes in docs

- src/index.js
**Summary**
Noticed what appears like a typo in the code.
> Fix code typo (style/styles).

- package.json
> chore(size-limit): Increase size limits to make them a bit loose

- examples/Styling/Readme.md
- styleguide.config.js
**Summary**
Add example for styling with styled-components
> add documentation for styling with styled-components

- LICENSE
> Updated year in LICENSE

- README.md
- examples/Accept/Readme.md
- examples/Basic/Readme.md
- examples/Fullscreen/Readme.md
- src/index.js
- src/index.spec.js
- src/utils/index.js
- src/utils/index.spec.js
- styleguide.config.js
**Summary**
Provide fix for https://github.com/react-dropzone/react-dropzone/pull/619#issuecomment-426573278.
No.
It also fixes some of the errors from the docs page.
> fix: fix file filter PR regression

- examples/Folders/Readme.md
- examples/PluginArchitecture/Readme.md
- package-lock.json
- package.json
- src/index.spec.js
- yarn.lock
**Summary**
Fixed the folder drop example (used a different lib) and added some tests, and added more docs on plugins.
No.
> fix: update folder drop example

- src/index.js
- src/index.spec.js
- src/utils/index.js
- src/utils/index.spec.js
- typings/react-dropzone.d.ts
**Summary**
A couple of fixes:
- do not use synthetic default imports in typings, close #696
- invoke onDrop when called from input change, close #698
- add more tests to increase coverage
No.
> fix: fix regression in PRs #673 and #695

- README.md
**Summary**
The example was using a variable that didn't exist. This PR fixes the variable.
I think the example could still be incomplete, compared to the actual tests.
I added a link to the actual test suite, because they're very helpful.
> Readme: Fix test example and link to test suite

- src/utils/index.js
- src/utils/index.spec.js
**Summary**
This should fix the check for file type when drag events occur.
No.
> fix: fix check for file types and close #726

- README.md
**Summary**
This package is totally maintained, yet there's a big, scary message at the top of the readme that makes it seems as though it isn't. I've removed that message!
No
> Remove note about missing maintainers

- package.json
- src/index.js
- src/index.spec.js
- src/utils/index.js
- src/utils/index.spec.js
> Make it compatible with React-like libs

- examples/Events/README.md
- package.json
- src/index.js
- styleguide.config.js
- yarn.lock
**Summary**
We're deprecating the `{disableClick}` property as the same result can be achieved using idiomatic js/react.
No.
> refactor: deprecate {disableClick}

- .github/ISSUE_TEMPLATE.md
**Summary**
Add a codesandbox sample to help users illustrate the issue they're experiencing.
No
> docs: add a codesandbox sample to get started when creating issues

- examples/accept/README.md
- examples/basic/README.md
- examples/class-component/README.md
- examples/events/README.md
- examples/file-dialog/README.md
- examples/plugins/README.md
- examples/previews/README.md
- examples/styling/README.md
- package.json
- yarn.lock
**Summary**
Also fix some issues with the docs in IE11:
- add semicolons to all docs as it causes some issues when compiled by react-styleguidist
- do not use Array.from() as IE11 does not support it
No.
> fix: update file-selector and close #776

- typings/react-dropzone.d.ts
- typings/tests/accept.tsx
**Summary**
Update `{accept}` prop type to match the prop-types declaration.
No.
> fix: fix type for {accept} prop and close #780

- README.md
- examples/file-dialog/README.md
- src/index.js
- src/index.spec.js
**Summary**
Keep backwards compatibility for users that still use the `<Dropzone>` component with refs.
No.
> fix: expose {open} on the ref and close #787

- src/utils/index.js
- src/utils/index.spec.js
**Summary**
Check if the `document` object exists to avoid errors in SSR.
@chill5018 I am still getting some errors after fixing this (`n` is not a function). I will need to investigate further.
No.
I am still working on this PR and will try to find why the other errors occur when using SSR.
> fix: check if document exists and fix #775

- src/index.spec.js
**Summary**
Add a test case for using a custom `{refKey}`.
No.
> test: add test case for {refKey}

- src/index.js
**Summary**
Fix a regression introduced with https://github.com/react-dropzone/react-dropzone/commit/5398f44f8fdcab8429b0c7769161bba72dad2800.
> fix: prevent errors in IE when dragEffect is set and close #791

- README.md
**Summary**
Add a note about the required react version.
No.
> docs: add a note about the required react version and close #795

- README.md
- examples/accept/README.md
- examples/basic/README.md
- examples/class-component/README.md
- examples/events/README.md
- examples/file-dialog/README.md
- examples/plugins/README.md
- examples/previews/README.md
- examples/styling/README.md
- examples/theme.css
- styleguide.config.js
**Summary**
Make dropzone examples more user friendly and simplify some of them.
No.
> docs: simplify examples and style all dropzones, closes #763

- src/__snapshots__/index.spec.js.snap
- src/index.js
- src/utils/index.js
- src/utils/index.spec.js
**Summary**
Removed the check for `{multiple}` attr support as it's supported in most modern browsers.
No.
> fix: remove check for multiple attr support and close #811

- examples/accept/README.md
- src/index.js
**Summary**
Set `{isDragActive}` during the drag operation.
> fix: set {isDragActive} on drag enter and close #819

- src/index.js
- src/index.spec.js
**Summary**
This will fix the issues with click event propagation to child DOM nodes.
> fix: fix click event propagation and close #826

- .github/ISSUE_TEMPLATE.md
**Summary**
Updated the link to issue codesandbox example.
No.
> docs: update codesandbox link in issue template

- src/index.js
**Summary**
Simplify code by using an existing React hook. Also reduces size.
No.
> refactor: don't re-implement useImperativeHandle

- README.md
> MOD: remove isDragActive since it's not used in this example

- README.md
- [ x] documentation
- [x ] Not relevant
**Summary**
i needed to build something real fast so i use the readme example to test my idea and it was throwing an error when ever i add multiple file. so i decided to fix it.
NO
NO
fixed uncaught error show in console when using the example file in readme doc
close #896
> fixed Uncaught (in promise) DOMException

- src/index.js
- src/utils/index.js
- src/utils/index.spec.js
**Summary**
This covers some edge cases when we check for file size constraints.
No.
> fix: cover for edge cases when checking file size and close #888

- examples/accept/README.md
- src/index.spec.js
- typings/tests/all.tsx
- typings/tests/events.tsx
> fix(examples): Update rejectedFiles to fileRejections in docs and tests

- examples/accept/README.md
> FIX SyntaxError on line 32

- examples/accept/README.md
> FIX SyntaxError on line 38

- src/utils/index.js
- typings/react-dropzone.d.ts
improve some typescript support for file error rejections
due to not changing any code just change a type, but running test
**Summary**
this merge request is motivated base on this issue
https://github.com/react-dropzone/react-dropzone/issues/988
No
> feat: 🎸 #988 Improve Typescript support for errors

- package-lock.json
- package.json
- yarn.lock
> fix(deps): update file-selector and close #1022

- README.md
- package-lock.json
- package.json
**Summary**
Add supported browsers.
Nope.
> fix: add supported browsers via browserslist config and close #630

- src/index.js
This PR:
- Adds validator prop to dependency array as unexpected behavior happens if onDropCb is not using last updated validator function.
**Summary**
We are not addressing the scenario when validator function changes externally and changes are not being applied, we need to use a unclean way to achieve the desired effect by mounting/unmounting the component.
> Add validator as part of dependency array to onDropCb

- examples/accept/README.md
- [x ] documentation
- [ x] Not relevant
**Summary**
'Across' was spelled 'accross'.
No.
It's a really minor thing. Feel free to ignore.
> fixed spelling of across

- README.md
- examples/events/README.md
**Summary**
Changed "om**m**it" to "omit"<sup>[[1]](https://www.wordnik.com/words/omit)[[2]](https://www.merriam-webster.com/dictionary/omit)</sup>.
No.
> Fix spelling error ("ommit"→"omit")

- README.md
**Summary**
Doka was renamed to Pintura so rename here as well
No
> Rename Doka to Pintura

- typings/react-dropzone.d.ts
**Summary**
Allow exposing error codes in a constant.
No.
> Modified type definitions for `FileError.code`

- .github/workflows/release.yml
**Summary**
Fix the failing release workflow due to incompatible node version.
No.
> ci: update node version for semantic-release

- examples/previews/README.md
**Summary**
Quick typo fix in the Preview documentation. Discovered this when I was modifying the useEffect for some async functions.
I sure hope not!
> Remove extra anonymous function in preview docs

- examples/no-jsx/README.md
- styleguide.config.js
**Summary**
Add an example of how to use this lib with react without JSX.
No/
Gotta merge https://github.com/react-dropzone/react-dropzone/pull/1123 first.
> docs: add example of using the lib without JSX and close #1101

- .eslintrc
- commitlint.config.js
- package.json
- rollup.config.js
- src/.eslintrc
- src/index.js
- src/index.spec.js
- src/utils/index.js
- src/utils/index.spec.js
- styleguide.config.js
- testSetup.js
- typings/.eslintrc
- typings/react-dropzone.d.ts
- typings/tests/accept.tsx
- typings/tests/all.tsx
- typings/tests/basic.tsx
- typings/tests/events.tsx
- typings/tests/file-dialog.tsx
- typings/tests/hook.tsx
- typings/tests/plugin.tsx
- typings/tests/refs.tsx
**Summary**
Fix the eslint configs and apply the rules to all codebase.
No.
> style: fix eslint configs and apply eslint rules

- typings/react-dropzone.d.ts
- typings/tests/all.tsx
**Summary**
Add type for useFsAccessApi option.
No.
> fix: add useFsAccessApi type

- README.md
- examples/accept/README.md
**Summary**
Clarify what the breaking change introduced in v12 means.
No.
> docs: clarify the breaking change in v12 and close #1138

- README.md
- package.json
- src/index.js
- src/index.spec.js
- testSetup.js
**Summary**
Check if in secure context when trying to use the FS access API.
No.
> fix: do not use FS access API if code is not in secure context

- README.md
**Summary**
Add a mention of netlify so we can apply for an open source account.
No.
> docs: mention hosting is done via netlify

- README.md
- package.json
- src/index.js
- src/index.spec.js
- typings/react-dropzone.d.ts
- yarn.lock
**Summary**
Add support for React 18.
No.
> feat: add support for React 18 and close #1121

- src/index.js
- src/index.spec.js
- typings/react-dropzone.d.ts
**Summary**
Allow users to auto focus the root element using `autoFocus`.
No.
> feat: add option to auto focus the root and close #1145

- src/index.js
- src/index.spec.js
- src/utils/index.js
- src/utils/index.spec.js
**Summary**
The custom validator wasn't running everywhere we do validation. So this PR just fixes that.
No.
> fix: run the custom validator everywhere validation is done

- typings/react-dropzone.d.ts
- typings/tests/all.tsx
**Summary**
Add missing `onError` type.
No.
> fix: add missing onError type

- package.json
**Summary**
Bump the file-selector dep to v0.6.
No.
> feat: bump file-selector to v0.6

- examples/previews/README.md
> docs: typo fix in previews page

- package.json
- yarn.lock
**Summary**
Bump attr-accept and file-selector deps.
No.
> feat: bump prod deps

- src/utils/index.js
- src/utils/index.spec.js
**Summary**
Address https://github.com/react-dropzone/react-dropzone/issues/1322.
No.
Depends on https://github.com/react-dropzone/react-dropzone/pull/1392.
> fix: allow application/* mime types

- package.json
- yarn.lock
**Summary**
Address https://github.com/react-dropzone/react-dropzone/issues/1346.
No.
> fix: update file-selector and close #1346

- src/__snapshots__/index.spec.js.snap
- src/index.js
**Summary**
Address https://github.com/react-dropzone/react-dropzone/issues/1268.
No.
> fix: visually hide the input and close #1268

- src/index.js
- src/index.spec.js
**Summary**
Address https://github.com/react-dropzone/react-dropzone/issues/1238.
No.
> fix: set {isDragRejected} on drop and close #1238

- README.md
**Summary**
Add a note about the caveats of using `useFsAccessApi`.
No.
> docs: add a note about the useFsAccessApi caveats

- src/utils/index.js
- src/utils/index.spec.js
**Summary**
Address https://github.com/react-dropzone/react-dropzone/issues/1221.
No.
> fix: fix wrong file type msg ux and close #1221
